### PR TITLE
my birthday

### PR DESCRIPTION
**Pull request by jimouris**
I added my birthday

### CODE REVIEW

**Comment by olgabrani** [comment]
Why did you delete birthday/dionysis.zindros.txt ?

**Comment by jimouris** [comment]
by mistake..

**Comment by dionyziz** [comment]
Please revert the commit deleting my birthday before I merge you ;)

**Comment by jimouris** [comment]
I tried to revert but it created a new commit. :/

**Comment by dionyziz** [comment]
A new commit is fine for this. Make sure the final diff just adds your birthday.

**Pull request closed without merging**
